# Generated by Django 5.1.3 on 2024-11-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('community', models.IntegerField(choices=[(1, 'Health'), (2, 'Software House'), (3, 'Sport')])),
                ('profile_image', models.TextField()),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_members', to='myapp.phonenumber')),
            ],
        ),
    ]
