# Generated by Django 5.1.3 on 2024-11-13 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='myapp.phonenumber')),
            ],
        ),
    ]
