# Generated by Django 5.1 on 2024-11-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
