# Generated by Django 5.1 on 2024-11-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_phonenumber_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='communitymember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'admin')), fields=('community',), name='unique_admin_per_community'),
        ),
    ]
