# Generated by Django 5.1 on 2024-11-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_communitymember_role_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='communitymember',
            constraint=models.UniqueConstraint(fields=('phone_number', 'community'), name='unique_phone_per_community'),
        ),
    ]
