# Generated by Django 5.1 on 2024-11-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_communitymember_unique_phone_per_community'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='communitymember',
            name='unique_admin_per_community',
        ),
        migrations.RemoveConstraint(
            model_name='communitymember',
            name='unique_phone_per_community',
        ),
    ]
