# Generated by Django 5.1 on 2024-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_communitymember_unique_admin_per_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
