# Generated by Django 5.1 on 2024-11-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_communitymember_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymember',
            name='status',
        ),
    ]
