# Generated by Django 5.1 on 2024-11-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_communitymember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
