# Generated by Django 5.1 on 2024-11-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_khitmah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khitmah',
            old_name='numberofkhitmah',
            new_name='khitmah_number',
        ),
        migrations.AddField(
            model_name='khitmah',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('completed', 'Completed')], default='incomplete', max_length=10),
        ),
    ]
