# Generated by Django 5.1 on 2024-11-14 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_numberofkhitmah_khitmah_khitmah_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khitmah',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('inprocess', 'In Process'), ('completed', 'Completed')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juz_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('completed', 'Completed')], default='incomplete', max_length=10)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.phonenumber')),
                ('khitmah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juz_list', to='myapp.khitmah')),
            ],
        ),
    ]
