# Generated by Django 5.1 on 2024-11-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_khitmah_status_juz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juz',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('inprocess', 'inprocess'), ('completed', 'Completed')], default='incomplete', max_length=10),
        ),
    ]
