# Generated by Django 5.1 on 2024-11-15 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_juz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juz',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('inprocess', 'In Process'), ('completed', 'Completed')], default='incomplete', max_length=10),
        ),
        migrations.CreateModel(
            name='NoticeboardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='noticeboard_posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phonenumber')),
            ],
        ),
    ]
