# Generated by Django 5.1 on 2024-11-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_juz_status_noticeboardpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
